### ISSUE TITLE
str -> unicode issue on python 2.7

### ISSUE THREAD

**Issue by nil0x42** [pohmelie/tinyantigate#3]
**`$ ./captcha-fuck.py captcha/tmpdu8JKS.jpg`**
```
Traceback (most recent call last):
  File "./captcha-fuck.py", line 15, in <module>
    status, text = antigate(API_KEY, captcha_bytes)
  File "/usr/lib/python2.7/site-packages/tinyantigate.py", line 91, in antigate
    return Antigate(key, host).run(captcha, timeout, count)
  File "/usr/lib/python2.7/site-packages/tinyantigate.py", line 73, in run
    status, captcha_id = self.send(captcha)
  File "/usr/lib/python2.7/site-packages/tinyantigate.py", line 44, in send
    "file": captcha,
  File "/usr/lib/python2.7/site-packages/tinyantigate.py", line 27, in parse_answer
    elif str.startswith(r.text, "OK|"):
TypeError: descriptor 'startswith' requires a 'str' object but received a 'unicode'
```

**Comment by pohmelie** [comment]
This library is only for python 3.

**Comment by nil0x42** [comment]
nice ! juste tried with python 3.6 and works fine.
Thanks
